#!/bin/bash

# Line spacing
echo

# Assignment 1: System Report Script
echo "System Report for $(hostname) generated by $(whoami), on $(date +%c)"

# Line break
echo

# System heading
# with included dash break
echo "System Information"
echo "------------------"

# Operating System
echo "OS: $(hostnamectl | grep 'Operating System:' | awk '{print $3,$4,$5}')"

# Uptime
echo "Uptime: $(uptime -p)"

# CPU in use
echo "CPU: $(lshw -C cpu 2>/dev/null | grep 'product:' | head -n 1 | awk '{print $2, $3, $4, $5, $6, $7, $8}') "
echo "RAM: $(free -h | awk '/Mem:/  {print $2}' ) "
echo "Disk(s): $(cat /sys/block/sda/device/vendor 2>/dev/null; cat /sys/block/sda/device/model 2>/dev/null; lsblk -n -o SIZE /dev/sda | head -n 1)"
echo "Video: $(lshw -C display 2>/dev/null | awk '/product:/ {print $2, $3, $4, $5, $6, $7, $8}')"
echo "Host Address: $(ip r | grep default | awk '{print $3}' | head -n 1) "
echo "Gateway IP: $(ip route | grep default | awk '{print $3}') "
echo "DNS Server: $(grep nameserver /etc/resolv.conf | awk '{print $2}') "

# Line Break
echo 

# System Status Title
# with included dash break
echo "System Status"
echo "-------------"

# List of users logged in
echo "Users Logged In: $(who | awk '{print $1}' | sort | paste -sd ",")"
echo "Disk Space: $(lsblk -o SIZE -e 7 | awk 'NR>1 {print $1}' | head -n 1)"
echo "Process Count: $(ps | wc -l)"
echo "Load Averages: $(uptime | awk -F'load average: ' '{print $2}') "
echo "Listening Network Port: $(netstat -tulpn 2>/dev/null | awk '/LISTEN|udp/{print $4}' | sed 's/.*://' | uniq |tr '\n' ',' | sed 's/,$//')"
echo "UFW Status: $(sudo -n ufw status 2>/dev/null || echo "sudo password is required")"

echo
