
#!/bin/bash -x

# Line spacing
echo

# Assignment 1: System Report Script
echo "System Report for $(hostname) generated by $(whoami), on $(date +%c)"

# Line break
echo

# System heading
# with included dash break
echo "System Information"
echo "------------------"

# Operating System
echo "OS: $(hostnamectl | grep 'Operating System:' | awk '{print $3,$4,$5}')"

# Uptime
echo "Uptime: $(uptime -p)"

# CPU in use
echo "CPU: "
echo "RAM: "
echo "Disk(s): "
echo "Video: "
echo "Host Address: "
echo "Gateway IP: $(ip route | grep default | awk '{print $3}') "
echo "DNS Server: "

# Line Break
echo 

# System Status Title
# with included dash break
echo "System Status"
echo "-------------"

# List of users logged in
echo "Users Logged In: $(who | awk '{print $1}' | sort | paste -sd ",")"
echo "Disk Space: "
echo "Process Count: "
echo "Load Averages: "
echo "Listening Network Port: "
echo "UFW Status: $(sudo -n ufw status 2>/dev/null || echo "sudo password is required")"

echo 
